let data = [
    {"id":1,"Ext":103,"Dept.":"Director ","Name":"Mr. Aamir Maqbool Sb"},
{"id":2,"Ext":104,"Dept.":"Director ","Name":"Mr. Harris Siddique Sb"},
{"id":3,"Ext":204,"Dept.":"Director ","Name":"Mr. Harris Siddique Sb"},
{"id":4,"Ext":105,"Dept.":"Director ","Name":"Mr. Shiraz Masood Sb"},
{"id":5,"Ext":108,"Dept.":"Director ","Name":"Mr. Sohaib Sb"},
{"id":6,"Ext":118,"Dept.":"----------","Name":"----------"},
{"id":7,"Ext":117,"Dept.":"Technical Director","Name":"Mr. Arshad Khan"},
{"id":8,"Ext":422,"Dept.":"A/C Chiller","Name":"Mr. Ashfaque Arain"},
{"id":9,"Ext":211,"Dept.":"A/C Chiller New","Name":"Mr. Abid"},
{"id":10,"Ext":279,"Dept.":"Harris Sb P.A","Name":"Mrs. Erum"},
{"id":11,"Ext":247,"Dept.":"Accounts","Name":"Mr. Danish"},
{"id":12,"Ext":147,"Dept.":"Accounts","Name":"Mr. Waqas"},
{"id":13,"Ext":154,"Dept.":"Accounts","Name":"Mr. Iqbal"},
{"id":14,"Ext":347,"Dept.":"Accounts","Name":"Yousuf Mubeen"},
{"id":15,"Ext":179,"Dept.":"Accounts","Name":"Mr. Fahad / Arsalan"},
{"id":16,"Ext":344,"Dept.":"Admin","Name":"Mr. Farooq"},
{"id":17,"Ext":162,"Dept.":"Hr","Name":"Mr. Faraz / Ali Shahid"},
{"id":18,"Ext":262,"Dept.":"Admin","Name":"Mr. SanaUllah /Sunjay "},
{"id":19,"Ext":362,"Dept.":"Admin","Name":"Mr. Hashim"},
{"id":20,"Ext":122,"Dept.":"Admin Manager","Name":"Mr. Major Asim"},
{"id":21,"Ext":178,"Dept.":"Auditor","Name":"Mr. Masood"},
{"id":22,"Ext":138,"Dept.":"Ball Warping","Name":"Mr. Anwar Warsi"},
{"id":23,"Ext":337,"Dept.":"Blanket Room ( Rope Dyeing)","Name":"Mr. Ashraf"},
{"id":24,"Ext":142,"Dept.":"Boiler","Name":"Mr. Saleem"},
{"id":25,"Ext":163,"Dept.":"Cashier","Name":"Mr. Shoaib / Talha."},
{"id":26,"Ext":132,"Dept.":"Central Lab","Name":"Mr. Naveed"},
{"id":27,"Ext":332,"Dept.":"Central Lab","Name":"All Users"},
{"id":28,"Ext":146,"Dept.":"Civil (Bilding Maintainance)","Name":"Mr. Saqib"},
{"id":29,"Ext":246,"Dept.":"Civil (Bilding Maintainance)","Name":"Mr. Saqib"},
{"id":30,"Ext":346,"Dept.":"Civil (Carpentar)","Name":"Mr.  Asif "},
{"id":31,"Ext":242,"Dept.":"Coal Boiler","Name":"Mr. Rasheed Ali"},
{"id":32,"Ext":170,"Dept.":"Compliance Office","Name":"Mr. Ubaid"},
{"id":33,"Ext":113,"Dept.":"Compliance Office","Name":"Mr. Shabab/Tariq/Waqas/Yasir/ Wajahat"},
{"id":34,"Ext":145,"Dept.":"Compressor","Name":"Mr. Nafees-ud-din"},
{"id":35,"Ext":192,"Dept.":"Confrence Room","Name":"-"},
{"id":36,"Ext":237,"Dept.":"Deying (Rope Dyeing New)","Name":"Mr. Omer"},
{"id":37,"Ext":133,"Dept.":"Dispatch","Name":"Mr. Ajman / faisal / Wahab"},
{"id":38,"Ext":198,"Dept.":"Dispatch cutting","Name":"Mr. Khushi"},
{"id":39,"Ext":168,"Dept.":"Dispensary","Name":"Mr. Rafiq"},
{"id":40,"Ext":137,"Dept.":"Dyeing Lab","Name":"Mr. Saqib"},
{"id":41,"Ext":338,"Dept.":"Dyeing Lab","Name":"Mr. Saqib"},
{"id":42,"Ext":223,"Dept.":"Dyeing Manager ","Name":"Mr. Salman"},
{"id":43,"Ext":123,"Dept.":"Dyeing Office","Name":"Mr. Nawaz"},
{"id":44,"Ext":232,"Dept.":"EHS","Name":"Mr. Irfan"},
{"id":45,"Ext":126,"Dept.":"Eelctrical","Name":"Electrical Staff"},
{"id":46,"Ext":226,"Dept.":"Electrical","Name":"Mr. Ali"},
{"id":47,"Ext":280,"Dept.":"Electrical Lab","Name":"Mr. Nazim/Mr.Asif"},
{"id":48,"Ext":180,"Dept.":"Electrical Manager","Name":"Mr. Ali Abbas"},
{"id":49,"Ext":380,"Dept.":"Electrical ","Name":"Mr. Sajid"},
{"id":50,"Ext":155,"Dept.":"Finance (Head Office)","Name":"Mr. Tanveer"},
{"id":51,"Ext":130,"Dept.":"Finishing","Name":"Mr. Safdar"},
{"id":52,"Ext":430,"Dept.":"Finishing","Name":"Mr. Tahir Shad"},
{"id":53,"Ext":230,"Dept.":"Finishing","Name":"Mr. Ali Sethar"},
{"id":54,"Ext":129,"Dept.":"Fire Fighting","Name":"Mr. Sohrab Baig"},
{"id":55,"Ext":229,"Dept.":"Fire Fighting","Name":"Fire Fighting"},
{"id":56,"Ext":185,"Dept.":"House Keeping","Name":"Mr. Mansukh"},
{"id":57,"Ext":222,"Dept.":"HR ","Name":"Mr. Loveraj"},
{"id":58,"Ext":322,"Dept.":"HR","Name":"Mrs. Maham"},
{"id":59,"Ext":300,"Dept.":"I.T","Name":"Anas/Mubashir/Zaib/Waqar/Anwer"},
{"id":60,"Ext":302,"Dept.":"I.T ","Name":"Anas/Mubashir/Zaib/Waqar/Anwer"},
{"id":61,"Ext":301,"Dept.":"I.T Manager ","Name":"Mr. Zeeshan"},
{"id":62,"Ext":160,"Dept.":"levis cordinator","Name":"Mr. Hameed"},
{"id":63,"Ext":326,"Dept.":"Maintainance Manager","Name":"Mr. Aziz Hayder"},
{"id":64,"Ext":141,"Dept.":"Maintainance","Name":"Mr. Arsalan"},
{"id":65,"Ext":241,"Dept.":"Maintainance","Name":"Mr. Deying Maintainance"},
{"id":66,"Ext":341,"Dept.":"Maintainance","Name":"Mr. Finishing Maintainance"},
{"id":67,"Ext":221,"Dept.":"Marketing","Name":"Mr. Haseeb / Ahsan ul Haq / Shariq"},
{"id":68,"Ext":121,"Dept.":"Marketing","Name":"Mr. Bilal"},
{"id":69,"Ext":156,"Dept.":"Marketing","Name":"Mr. Ahsan / Mrs. Esha"},
{"id":70,"Ext":256,"Dept.":"Marketing ","Name":"Mr. Sharjeel / Mrs. Iqra"},
{"id":71,"Ext":356,"Dept.":"Marketing ","Name":"Mr. Shakeeb"},
{"id":72,"Ext":456,"Dept.":"Marketing","Name":"Mr. Sheheryar"},
{"id":73,"Ext":314,"Dept.":"Digital Marketing","Name":"Mr. Shiraz"},
{"id":74,"Ext":340,"Dept.":"Digital Marketing","Name":"Mr. Adeel / Aftab / Mrs. Zoya"},
{"id":75,"Ext":271,"Dept.":"Marketing ","Name":"Mr. Faizan "},
{"id":76,"Ext":172,"Dept.":"Marketing","Name":"Mr. Daniyal"},
{"id":77,"Ext":173,"Dept.":"Marketing","Name":"Mr. Faraz / Jawwad"},
{"id":78,"Ext":174,"Dept.":"Marketing","Name":"Mr. Zulfiqar / Rao Junaid"},
{"id":79,"Ext":159,"Dept.":"Marketing","Name":"Mr. Farhan / Faisal"},
{"id":80,"Ext":107,"Dept.":"Marketing","Name":"Mrs. Jannat"},
{"id":81,"Ext":171,"Dept.":"Marketing","Name":"Mr. Ashraf / Faizan Khan"},
{"id":82,"Ext":161,"Dept.":"Marketing","Name":"Mr. Rizwan Mulla"},
{"id":83,"Ext":166,"Dept.":"Marketing","Name":"Mr. Sultan / Mrs. Gul Nayab"},
{"id":84,"Ext":267,"Dept.":"Mezenine","Name":"Kitchen"},
{"id":85,"Ext":167,"Dept.":"Kitchen H/O","Name":"Kitchen"},
{"id":86,"Ext":420,"Dept.":"Q.C Inspection","Name":"Mr. Waheed"},
{"id":87,"Ext":342,"Dept.":"Power House","Name":"Power House"}
]